version: "3"

services:
  nginx:
    image: nginx:1.21.0-alpine
    container_name: nginx_webserver
    tty: true
    depends_on:
      - postgres
      - server
      - pgadmin
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - appNetwork

  postgres:
    image: postgres:13.2-alpine
    container_name: postgresdb
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_PASSWORD}"
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - appNetwork

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    volumes:
      - postgres-admin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
      PGADMIN_LISTEN_PORT: 7000
    networks:
      - appNetwork
    links:
      - "postgres:pgsql-server"


  server:
    build:
      context: .
    container_name: server
    depends_on:
      - postgres
    volumes:
      - .:/app
    networks:
      - appNetwork



networks:
  appNetwork:
    driver: bridge

volumes:
  next-data:
  pg-data:
  pg-admin-data: